---

# curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
# sudo apt update
# sudo apt install gh

- name: add guthub cli apt key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present

- name: add github cli apt repository
  apt_repository:
    repo: deb [arch=amd64] https://cli.github.com/packages stable main
    state: present

- name: install gh cli package
  apt:
    name:
      - gh
    state: latest
    update_cache: yes
